name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ {"os": ubuntu-latest, short: linux}]
        compiler: [gcc,clang]

    runs-on: ${{matrix.os.os}}

    steps:
    - uses: actions/checkout@v3
    
    - name: "Set environmental variables"
      shell: bash
      run: |
        echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
        
    - name: Install nasm
      run: sudo apt-get install -y nasm

    - name: Configure CMake
      run: cmake --preset ${{matrix.os.short}}-${{matrix.compiler}}-release

    - name: Build
      run: cmake --build --preset ${{matrix.os.short}}-${{matrix.compiler}}-release

    - name: Test
      run: ctest --preset ${{matrix.os.short}}-${{matrix.compiler}}-release

